
[package]
name = "game_dylib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
new = { path = "../game", default-features = false }

[features]
default = ["new/default"]
dylib-engine = ["new/dylib-engine"]
